language: scala
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
services:
  - elasticsearch
before_script:
  - cp conf/travis.conf conf/test.conf
branches:
  only:
    - master
