language: scala
jdk: oraclejdk8
services:
  - elasticsearch
before_script:
  - echo -e "\nes.host.server=\"localhost\"\nes.host.port=\"9300\"\nes.index.name=\"oerworldmap\"\nes.index.type=\"worldmap\"\nes.cluster.name=\"elasticsearch\"\n" > conf/application.conf